// DO NOT EDIT! This is an autogenerated file. All changes will be
// overwritten!

//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Collections;
using System.Runtime.InteropServices;

namespace VidyoClient
{
	public class CameraEffectStatsFactory
	{
		public static CameraEffectStats Create()
		{
			return new CameraEffectStats(IntPtr.Zero);
		}
		public static void Destroy(CameraEffectStats obj)
		{
		}
	}
	public class CameraEffectStats{
#if __IOS__
		const string importLib = "__Internal";
#else
		const string importLib = "libVidyoClient";
#endif
		private IntPtr objPtr; // opaque VidyoCameraEffectStats reference.
		public IntPtr GetObjectPtr(){

			VidyoCameraEffectStatsSetaverageBanubaProcessingTimeNative(objPtr, averageBanubaProcessingTime);
			VidyoCameraEffectStatsSetaverageBufferReadingTimeNative(objPtr, averageBufferReadingTime);
			VidyoCameraEffectStatsSetaverageFrameProcessingTimeNative(objPtr, averageFrameProcessingTime);
			VidyoCameraEffectStatsSetframesDroppedNative(objPtr, framesDropped);
			VidyoCameraEffectStatsSetmaxBanubaProcessingTimeNative(objPtr, maxBanubaProcessingTime);
			VidyoCameraEffectStatsSetmaxBufferReadingTimeNative(objPtr, maxBufferReadingTime);
			VidyoCameraEffectStatsSetmaxFrameProcessingTimeNative(objPtr, maxFrameProcessingTime);

			return objPtr;
		}
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern double VidyoCameraEffectStatsGetaverageBanubaProcessingTimeNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoCameraEffectStatsSetaverageBanubaProcessingTimeNative(IntPtr obj, double averageBanubaProcessingTime);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern double VidyoCameraEffectStatsGetaverageBufferReadingTimeNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoCameraEffectStatsSetaverageBufferReadingTimeNative(IntPtr obj, double averageBufferReadingTime);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern double VidyoCameraEffectStatsGetaverageFrameProcessingTimeNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoCameraEffectStatsSetaverageFrameProcessingTimeNative(IntPtr obj, double averageFrameProcessingTime);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern uint VidyoCameraEffectStatsGetframesDroppedNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoCameraEffectStatsSetframesDroppedNative(IntPtr obj, uint framesDropped);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern double VidyoCameraEffectStatsGetmaxBanubaProcessingTimeNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoCameraEffectStatsSetmaxBanubaProcessingTimeNative(IntPtr obj, double maxBanubaProcessingTime);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern double VidyoCameraEffectStatsGetmaxBufferReadingTimeNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoCameraEffectStatsSetmaxBufferReadingTimeNative(IntPtr obj, double maxBufferReadingTime);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern double VidyoCameraEffectStatsGetmaxFrameProcessingTimeNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoCameraEffectStatsSetmaxFrameProcessingTimeNative(IntPtr obj, double maxFrameProcessingTime);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		public static extern IntPtr VidyoCameraEffectStatsConstructCopyNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		public static extern IntPtr VidyoCameraEffectStatsConstructDefaultNative();

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		public static extern void VidyoCameraEffectStatsDestructNative(IntPtr obj);

		public double averageBanubaProcessingTime;
		public double averageBufferReadingTime;
		public double averageFrameProcessingTime;
		public uint framesDropped;
		public double maxBanubaProcessingTime;
		public double maxBufferReadingTime;
		public double maxFrameProcessingTime;
		public CameraEffectStats(IntPtr obj){
			if(obj == IntPtr.Zero) {
				objPtr = VidyoCameraEffectStatsConstructDefaultNative();
			}
			else {
				objPtr = VidyoCameraEffectStatsConstructCopyNative(obj);
			}

			averageBanubaProcessingTime = VidyoCameraEffectStatsGetaverageBanubaProcessingTimeNative(objPtr);
			averageBufferReadingTime = VidyoCameraEffectStatsGetaverageBufferReadingTimeNative(objPtr);
			averageFrameProcessingTime = VidyoCameraEffectStatsGetaverageFrameProcessingTimeNative(objPtr);
			framesDropped = VidyoCameraEffectStatsGetframesDroppedNative(objPtr);
			maxBanubaProcessingTime = VidyoCameraEffectStatsGetmaxBanubaProcessingTimeNative(objPtr);
			maxBufferReadingTime = VidyoCameraEffectStatsGetmaxBufferReadingTimeNative(objPtr);
			maxFrameProcessingTime = VidyoCameraEffectStatsGetmaxFrameProcessingTimeNative(objPtr);
		}
		~CameraEffectStats() {
			VidyoCameraEffectStatsDestructNative(objPtr);
		 }
	};
}
