// DO NOT EDIT! This is an autogenerated file. All changes will be
// overwritten!

//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Collections;
using System.Runtime.InteropServices;

namespace VidyoClient
{
	public class EndpointCameraEffectInfoFactory
	{
		public static EndpointCameraEffectInfo Create()
		{
			return new EndpointCameraEffectInfo(IntPtr.Zero);
		}
		public static void Destroy(EndpointCameraEffectInfo obj)
		{
		}
	}
	public class EndpointCameraEffectInfo{
#if __IOS__
		const string importLib = "__Internal";
#else
		const string importLib = "libVidyoClient";
#endif
		private IntPtr objPtr; // opaque VidyoEndpointCameraEffectInfo reference.
		public IntPtr GetObjectPtr(){
			IntPtr nPathToEffect = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(pathToEffect ?? string.Empty);
			IntPtr nPathToResources = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(pathToResources ?? string.Empty);
			IntPtr nToken = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(token ?? string.Empty);
			IntPtr nVirtualBackgroundPicture = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(virtualBackgroundPicture ?? string.Empty);

			VidyoEndpointCameraEffectInfoSetblurIntensityNative(objPtr, blurIntensity);
			VidyoEndpointCameraEffectInfoSeteffectTypeNative(objPtr, effectType);
			VidyoEndpointCameraEffectInfoSetpathToEffectNative(objPtr, nPathToEffect);
			VidyoEndpointCameraEffectInfoSetpathToResourcesNative(objPtr, nPathToResources);
			VidyoEndpointCameraEffectInfoSettokenNative(objPtr, nToken);
			VidyoEndpointCameraEffectInfoSetvirtualBackgroundPictureNative(objPtr, nVirtualBackgroundPicture);

			Marshal.FreeHGlobal(nVirtualBackgroundPicture);
			Marshal.FreeHGlobal(nToken);
			Marshal.FreeHGlobal(nPathToResources);
			Marshal.FreeHGlobal(nPathToEffect);
			return objPtr;
		}
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern uint VidyoEndpointCameraEffectInfoGetblurIntensityNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoEndpointCameraEffectInfoSetblurIntensityNative(IntPtr obj, uint blurIntensity);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I4)]
		private static extern Endpoint.EndpointCameraEffectType VidyoEndpointCameraEffectInfoGeteffectTypeNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoEndpointCameraEffectInfoSeteffectTypeNative(IntPtr obj, Endpoint.EndpointCameraEffectType effectType);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoEndpointCameraEffectInfoGetpathToEffectNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoEndpointCameraEffectInfoSetpathToEffectNative(IntPtr obj, IntPtr pathToEffect);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoEndpointCameraEffectInfoGetpathToResourcesNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoEndpointCameraEffectInfoSetpathToResourcesNative(IntPtr obj, IntPtr pathToResources);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoEndpointCameraEffectInfoGettokenNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoEndpointCameraEffectInfoSettokenNative(IntPtr obj, IntPtr token);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoEndpointCameraEffectInfoGetvirtualBackgroundPictureNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoEndpointCameraEffectInfoSetvirtualBackgroundPictureNative(IntPtr obj, IntPtr virtualBackgroundPicture);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		public static extern IntPtr VidyoEndpointCameraEffectInfoConstructCopyNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		public static extern IntPtr VidyoEndpointCameraEffectInfoConstructDefaultNative();

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		public static extern void VidyoEndpointCameraEffectInfoDestructNative(IntPtr obj);

		public uint blurIntensity;
		public Endpoint.EndpointCameraEffectType effectType;
		public String pathToEffect;
		public String pathToResources;
		public String token;
		public String virtualBackgroundPicture;
		public EndpointCameraEffectInfo(IntPtr obj){
			if(obj == IntPtr.Zero) {
				objPtr = VidyoEndpointCameraEffectInfoConstructDefaultNative();
			}
			else {
				objPtr = VidyoEndpointCameraEffectInfoConstructCopyNative(obj);
			}

			blurIntensity = VidyoEndpointCameraEffectInfoGetblurIntensityNative(objPtr);
			effectType = VidyoEndpointCameraEffectInfoGeteffectTypeNative(objPtr);
			pathToEffect = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoEndpointCameraEffectInfoGetpathToEffectNative(objPtr));
			pathToResources = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoEndpointCameraEffectInfoGetpathToResourcesNative(objPtr));
			token = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoEndpointCameraEffectInfoGettokenNative(objPtr));
			virtualBackgroundPicture = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoEndpointCameraEffectInfoGetvirtualBackgroundPictureNative(objPtr));
		}
		~EndpointCameraEffectInfo() {
			VidyoEndpointCameraEffectInfoDestructNative(objPtr);
		 }
	};
}
