// DO NOT EDIT! This is an autogenerated file. All changes will be
// overwritten!

//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Collections;
using System.Runtime.InteropServices;

namespace VidyoClient
{
	public class EndpointShareOptionsFactory
	{
		public static EndpointShareOptions Create()
		{
			return new EndpointShareOptions(IntPtr.Zero);
		}
		public static void Destroy(EndpointShareOptions obj)
		{
		}
	}
	public class EndpointShareOptions{
#if __IOS__
		const string importLib = "__Internal";
#else
		const string importLib = "libVidyoClient";
#endif
		private IntPtr objPtr; // opaque VidyoEndpointShareOptions reference.
		public IntPtr GetObjectPtr(){

			VidyoEndpointShareOptionsSetenableAudioNative(objPtr, enableAudio);
			VidyoEndpointShareOptionsSetenableHighFramerateNative(objPtr, enableHighFramerate);

			return objPtr;
		}
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I1)]
		private static extern Boolean VidyoEndpointShareOptionsGetenableAudioNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoEndpointShareOptionsSetenableAudioNative(IntPtr obj, Boolean enableAudio);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I1)]
		private static extern Boolean VidyoEndpointShareOptionsGetenableHighFramerateNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoEndpointShareOptionsSetenableHighFramerateNative(IntPtr obj, Boolean enableHighFramerate);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		public static extern IntPtr VidyoEndpointShareOptionsConstructCopyNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		public static extern IntPtr VidyoEndpointShareOptionsConstructDefaultNative();

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		public static extern void VidyoEndpointShareOptionsDestructNative(IntPtr obj);

		public Boolean enableAudio;
		public Boolean enableHighFramerate;
		public EndpointShareOptions(IntPtr obj){
			if(obj == IntPtr.Zero) {
				objPtr = VidyoEndpointShareOptionsConstructDefaultNative();
			}
			else {
				objPtr = VidyoEndpointShareOptionsConstructCopyNative(obj);
			}

			enableAudio = VidyoEndpointShareOptionsGetenableAudioNative(objPtr);
			enableHighFramerate = VidyoEndpointShareOptionsGetenableHighFramerateNative(objPtr);
		}
		~EndpointShareOptions() {
			VidyoEndpointShareOptionsDestructNative(objPtr);
		 }
	};
}
