// DO NOT EDIT! This is an autogenerated file. All changes will be
// overwritten!

//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Collections;
using System.Runtime.InteropServices;

namespace VidyoClient
{
	public class NetworkServiceCAInfoFactory
	{
		public static NetworkServiceCAInfo Create()
		{
			return new NetworkServiceCAInfo(IntPtr.Zero);
		}
		public static void Destroy(NetworkServiceCAInfo obj)
		{
		}
	}
	public class NetworkServiceCAInfo{
#if __IOS__
		const string importLib = "__Internal";
#else
		const string importLib = "libVidyoClient";
#endif
		private IntPtr objPtr; // opaque VidyoNetworkServiceCAInfo reference.
		public IntPtr GetObjectPtr(){
			IntPtr nCaFileContent = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(caFileContent ?? string.Empty);
			IntPtr nCaFilePath = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(caFilePath ?? string.Empty);

			VidyoNetworkServiceCAInfoSetcaFileContentNative(objPtr, nCaFileContent);
			VidyoNetworkServiceCAInfoSetcaFilePathNative(objPtr, nCaFilePath);

			Marshal.FreeHGlobal(nCaFilePath);
			Marshal.FreeHGlobal(nCaFileContent);
			return objPtr;
		}
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoNetworkServiceCAInfoGetcaFileContentNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoNetworkServiceCAInfoSetcaFileContentNative(IntPtr obj, IntPtr caFileContent);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoNetworkServiceCAInfoGetcaFilePathNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoNetworkServiceCAInfoSetcaFilePathNative(IntPtr obj, IntPtr caFilePath);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		public static extern IntPtr VidyoNetworkServiceCAInfoConstructCopyNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		public static extern IntPtr VidyoNetworkServiceCAInfoConstructDefaultNative();

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		public static extern void VidyoNetworkServiceCAInfoDestructNative(IntPtr obj);

		public String caFileContent;
		public String caFilePath;
		public NetworkServiceCAInfo(IntPtr obj){
			if(obj == IntPtr.Zero) {
				objPtr = VidyoNetworkServiceCAInfoConstructDefaultNative();
			}
			else {
				objPtr = VidyoNetworkServiceCAInfoConstructCopyNative(obj);
			}

			caFileContent = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoNetworkServiceCAInfoGetcaFileContentNative(objPtr));
			caFilePath = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoNetworkServiceCAInfoGetcaFilePathNative(objPtr));
		}
		~NetworkServiceCAInfo() {
			VidyoNetworkServiceCAInfoDestructNative(objPtr);
		 }
	};
}
