// DO NOT EDIT! This is an autogenerated file. All changes will be
// overwritten!

//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Collections;
using System.Runtime.InteropServices;

namespace VidyoClient
{
	public class NetworkService: IDisposable {
		private bool disposed = false; 
#if __IOS__
		const string importLib = "__Internal";
#else
		const string importLib = "libVidyoClient";
#endif
		private IntPtr objPtr; // opaque VidyoNetworkService reference.
		public IntPtr GetObjectPtr(){
			return objPtr;
		}
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoNetworkServiceConstructNative(IntPtr caInfo);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoNetworkServiceConstructCopyNative(IntPtr other);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoNetworkServiceDestructNative(IntPtr networkService);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I4)]
		private static extern NetworkServiceErrorCode VidyoNetworkServiceHttpRequestASyncNative(IntPtr networkService, IntPtr requestHeader, ResponseCB responseCB, ulong userData);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		public static extern IntPtr VidyoNetworkServiceGetUserDataNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		public static extern void VidyoNetworkServiceSetUserDataNative(IntPtr obj, IntPtr userData);

		[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
		private delegate void ResponseCB(IntPtr networkService, IntPtr httpResponseHeader, ulong userData);
		private ResponseCB _mResponseCB;
		public enum NetworkServiceErrorCode{
			NetworkserviceERRORCODE_Ok,
			NetworkserviceERRORCODE_Error,
			NetworkserviceERRORCODE_MandatoryParamsMissing,
			NetworkserviceERRORCODE_BadRequest,
			NetworkserviceERRORCODE_MaxSimultaneousRequestsReached,
			NetworkserviceERRORCODE_HttpRequestTimeOut
		}
		public interface IHttpRequestASync{

			void ResponseCB(NetworkServiceResponseHeader httpResponseHeader, ulong userData);
		}
		public class NetworkServiceRequestHeaderFactory
		{
			public static NetworkServiceRequestHeader Create()
			{
				return new NetworkServiceRequestHeader(IntPtr.Zero);
			}
			public static void Destroy(NetworkServiceRequestHeader obj)
			{
			}
		}
		public class NetworkServiceRequestHeader{
#if __IOS__
			const string importLib = "__Internal";
#else
			const string importLib = "libVidyoClient";
#endif
			private IntPtr objPtr; // opaque VidyoNetworkServiceRequestHeader reference.
			public IntPtr GetObjectPtr(){
				IntPtr nRequestContentType = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(requestContentType ?? string.Empty);
				IntPtr nRequestMethod = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(requestMethod ?? string.Empty);
				IntPtr nRequestNumber = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(requestNumber ?? string.Empty);
				IntPtr nRequestPayload = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(requestPayload ?? string.Empty);
				IntPtr nRequestUrl = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(requestUrl ?? string.Empty);
				IntPtr nUserAuthToken = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(userAuthToken ?? string.Empty);
				IntPtr nUserAuthUserName = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(userAuthUserName ?? string.Empty);
				IntPtr nUserAuthUserPassword = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(userAuthUserPassword ?? string.Empty);
				IntPtr nWebProxyUserName = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(webProxyUserName ?? string.Empty);
				IntPtr nWebProxyUserPassword = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(webProxyUserPassword ?? string.Empty);

				VidyoNetworkServiceRequestHeaderSetrequestContentTypeNative(objPtr, nRequestContentType);
				VidyoNetworkServiceRequestHeaderSetrequestMethodNative(objPtr, nRequestMethod);
				VidyoNetworkServiceRequestHeaderSetrequestNumberNative(objPtr, nRequestNumber);
				VidyoNetworkServiceRequestHeaderSetrequestPayloadNative(objPtr, nRequestPayload);
				VidyoNetworkServiceRequestHeaderSetrequestUrlNative(objPtr, nRequestUrl);
				VidyoNetworkServiceRequestHeaderSetuserAuthTokenNative(objPtr, nUserAuthToken);
				VidyoNetworkServiceRequestHeaderSetuserAuthUserNameNative(objPtr, nUserAuthUserName);
				VidyoNetworkServiceRequestHeaderSetuserAuthUserPasswordNative(objPtr, nUserAuthUserPassword);
				VidyoNetworkServiceRequestHeaderSetwebProxyUserNameNative(objPtr, nWebProxyUserName);
				VidyoNetworkServiceRequestHeaderSetwebProxyUserPasswordNative(objPtr, nWebProxyUserPassword);

				Marshal.FreeHGlobal(nWebProxyUserPassword);
				Marshal.FreeHGlobal(nWebProxyUserName);
				Marshal.FreeHGlobal(nUserAuthUserPassword);
				Marshal.FreeHGlobal(nUserAuthUserName);
				Marshal.FreeHGlobal(nUserAuthToken);
				Marshal.FreeHGlobal(nRequestUrl);
				Marshal.FreeHGlobal(nRequestPayload);
				Marshal.FreeHGlobal(nRequestNumber);
				Marshal.FreeHGlobal(nRequestMethod);
				Marshal.FreeHGlobal(nRequestContentType);
				return objPtr;
			}
			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			private static extern IntPtr VidyoNetworkServiceRequestHeaderGetrequestContentTypeNative(IntPtr obj);

			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			private static extern void VidyoNetworkServiceRequestHeaderSetrequestContentTypeNative(IntPtr obj, IntPtr requestContentType);

			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			private static extern IntPtr VidyoNetworkServiceRequestHeaderGetrequestMethodNative(IntPtr obj);

			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			private static extern void VidyoNetworkServiceRequestHeaderSetrequestMethodNative(IntPtr obj, IntPtr requestMethod);

			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			private static extern IntPtr VidyoNetworkServiceRequestHeaderGetrequestNumberNative(IntPtr obj);

			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			private static extern void VidyoNetworkServiceRequestHeaderSetrequestNumberNative(IntPtr obj, IntPtr requestNumber);

			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			private static extern IntPtr VidyoNetworkServiceRequestHeaderGetrequestPayloadNative(IntPtr obj);

			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			private static extern void VidyoNetworkServiceRequestHeaderSetrequestPayloadNative(IntPtr obj, IntPtr requestPayload);

			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			private static extern IntPtr VidyoNetworkServiceRequestHeaderGetrequestUrlNative(IntPtr obj);

			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			private static extern void VidyoNetworkServiceRequestHeaderSetrequestUrlNative(IntPtr obj, IntPtr requestUrl);

			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			private static extern IntPtr VidyoNetworkServiceRequestHeaderGetuserAuthTokenNative(IntPtr obj);

			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			private static extern void VidyoNetworkServiceRequestHeaderSetuserAuthTokenNative(IntPtr obj, IntPtr userAuthToken);

			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			private static extern IntPtr VidyoNetworkServiceRequestHeaderGetuserAuthUserNameNative(IntPtr obj);

			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			private static extern void VidyoNetworkServiceRequestHeaderSetuserAuthUserNameNative(IntPtr obj, IntPtr userAuthUserName);

			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			private static extern IntPtr VidyoNetworkServiceRequestHeaderGetuserAuthUserPasswordNative(IntPtr obj);

			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			private static extern void VidyoNetworkServiceRequestHeaderSetuserAuthUserPasswordNative(IntPtr obj, IntPtr userAuthUserPassword);

			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			private static extern IntPtr VidyoNetworkServiceRequestHeaderGetwebProxyUserNameNative(IntPtr obj);

			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			private static extern void VidyoNetworkServiceRequestHeaderSetwebProxyUserNameNative(IntPtr obj, IntPtr webProxyUserName);

			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			private static extern IntPtr VidyoNetworkServiceRequestHeaderGetwebProxyUserPasswordNative(IntPtr obj);

			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			private static extern void VidyoNetworkServiceRequestHeaderSetwebProxyUserPasswordNative(IntPtr obj, IntPtr webProxyUserPassword);

			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			public static extern IntPtr VidyoNetworkServiceRequestHeaderConstructCopyNative(IntPtr obj);

			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			public static extern IntPtr VidyoNetworkServiceRequestHeaderConstructDefaultNative();

			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			public static extern void VidyoNetworkServiceRequestHeaderDestructNative(IntPtr obj);

			public String requestContentType;
			public String requestMethod;
			public String requestNumber;
			public String requestPayload;
			public String requestUrl;
			public String userAuthToken;
			public String userAuthUserName;
			public String userAuthUserPassword;
			public String webProxyUserName;
			public String webProxyUserPassword;
			public NetworkServiceRequestHeader(IntPtr obj){
				if(obj == IntPtr.Zero) {
					objPtr = VidyoNetworkServiceRequestHeaderConstructDefaultNative();
				}
				else {
					objPtr = VidyoNetworkServiceRequestHeaderConstructCopyNative(obj);
				}

				requestContentType = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoNetworkServiceRequestHeaderGetrequestContentTypeNative(objPtr));
				requestMethod = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoNetworkServiceRequestHeaderGetrequestMethodNative(objPtr));
				requestNumber = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoNetworkServiceRequestHeaderGetrequestNumberNative(objPtr));
				requestPayload = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoNetworkServiceRequestHeaderGetrequestPayloadNative(objPtr));
				requestUrl = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoNetworkServiceRequestHeaderGetrequestUrlNative(objPtr));
				userAuthToken = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoNetworkServiceRequestHeaderGetuserAuthTokenNative(objPtr));
				userAuthUserName = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoNetworkServiceRequestHeaderGetuserAuthUserNameNative(objPtr));
				userAuthUserPassword = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoNetworkServiceRequestHeaderGetuserAuthUserPasswordNative(objPtr));
				webProxyUserName = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoNetworkServiceRequestHeaderGetwebProxyUserNameNative(objPtr));
				webProxyUserPassword = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoNetworkServiceRequestHeaderGetwebProxyUserPasswordNative(objPtr));
			}
			~NetworkServiceRequestHeader() {
				VidyoNetworkServiceRequestHeaderDestructNative(objPtr);
			 }
		};
		public class NetworkServiceResponseHeaderFactory
		{
			public static NetworkServiceResponseHeader Create()
			{
				return new NetworkServiceResponseHeader(IntPtr.Zero);
			}
			public static void Destroy(NetworkServiceResponseHeader obj)
			{
			}
		}
		public class NetworkServiceResponseHeader{
#if __IOS__
			const string importLib = "__Internal";
#else
			const string importLib = "libVidyoClient";
#endif
			private IntPtr objPtr; // opaque VidyoNetworkServiceResponseHeader reference.
			public IntPtr GetObjectPtr(){
				IntPtr nHttpResponseContent = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(httpResponseContent ?? string.Empty);
				IntPtr nHttpResponseContentType = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(httpResponseContentType ?? string.Empty);
				IntPtr nRequestNumber = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(requestNumber ?? string.Empty);
				IntPtr nWebProxyIPAddress = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(webProxyIPAddress ?? string.Empty);

				VidyoNetworkServiceResponseHeaderSeterrorCodeNative(objPtr, errorCode);
				VidyoNetworkServiceResponseHeaderSethttpResponseContentNative(objPtr, nHttpResponseContent);
				VidyoNetworkServiceResponseHeaderSethttpResponseContentSizeNative(objPtr, httpResponseContentSize);
				VidyoNetworkServiceResponseHeaderSethttpResponseContentTypeNative(objPtr, nHttpResponseContentType);
				VidyoNetworkServiceResponseHeaderSethttpStatusCodeNative(objPtr, httpStatusCode);
				VidyoNetworkServiceResponseHeaderSetrequestNumberNative(objPtr, nRequestNumber);
				VidyoNetworkServiceResponseHeaderSetwebProxyIPAddressNative(objPtr, nWebProxyIPAddress);
				VidyoNetworkServiceResponseHeaderSetwebProxyIPPortNative(objPtr, webProxyIPPort);

				Marshal.FreeHGlobal(nWebProxyIPAddress);
				Marshal.FreeHGlobal(nRequestNumber);
				Marshal.FreeHGlobal(nHttpResponseContentType);
				Marshal.FreeHGlobal(nHttpResponseContent);
				return objPtr;
			}
			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			[return: MarshalAs(UnmanagedType.I4)]
			private static extern NetworkService.NetworkServiceErrorCode VidyoNetworkServiceResponseHeaderGeterrorCodeNative(IntPtr obj);

			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			private static extern void VidyoNetworkServiceResponseHeaderSeterrorCodeNative(IntPtr obj, NetworkService.NetworkServiceErrorCode errorCode);

			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			private static extern IntPtr VidyoNetworkServiceResponseHeaderGethttpResponseContentNative(IntPtr obj);

			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			private static extern void VidyoNetworkServiceResponseHeaderSethttpResponseContentNative(IntPtr obj, IntPtr httpResponseContent);

			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			private static extern uint VidyoNetworkServiceResponseHeaderGethttpResponseContentSizeNative(IntPtr obj);

			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			private static extern void VidyoNetworkServiceResponseHeaderSethttpResponseContentSizeNative(IntPtr obj, uint httpResponseContentSize);

			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			private static extern IntPtr VidyoNetworkServiceResponseHeaderGethttpResponseContentTypeNative(IntPtr obj);

			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			private static extern void VidyoNetworkServiceResponseHeaderSethttpResponseContentTypeNative(IntPtr obj, IntPtr httpResponseContentType);

			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			private static extern uint VidyoNetworkServiceResponseHeaderGethttpStatusCodeNative(IntPtr obj);

			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			private static extern void VidyoNetworkServiceResponseHeaderSethttpStatusCodeNative(IntPtr obj, uint httpStatusCode);

			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			private static extern IntPtr VidyoNetworkServiceResponseHeaderGetrequestNumberNative(IntPtr obj);

			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			private static extern void VidyoNetworkServiceResponseHeaderSetrequestNumberNative(IntPtr obj, IntPtr requestNumber);

			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			private static extern IntPtr VidyoNetworkServiceResponseHeaderGetwebProxyIPAddressNative(IntPtr obj);

			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			private static extern void VidyoNetworkServiceResponseHeaderSetwebProxyIPAddressNative(IntPtr obj, IntPtr webProxyIPAddress);

			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			private static extern uint VidyoNetworkServiceResponseHeaderGetwebProxyIPPortNative(IntPtr obj);

			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			private static extern void VidyoNetworkServiceResponseHeaderSetwebProxyIPPortNative(IntPtr obj, uint webProxyIPPort);

			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			public static extern IntPtr VidyoNetworkServiceResponseHeaderConstructCopyNative(IntPtr obj);

			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			public static extern IntPtr VidyoNetworkServiceResponseHeaderConstructDefaultNative();

			[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
			public static extern void VidyoNetworkServiceResponseHeaderDestructNative(IntPtr obj);

			public NetworkService.NetworkServiceErrorCode errorCode;
			public String httpResponseContent;
			public uint httpResponseContentSize;
			public String httpResponseContentType;
			public uint httpStatusCode;
			public String requestNumber;
			public String webProxyIPAddress;
			public uint webProxyIPPort;
			public NetworkServiceResponseHeader(IntPtr obj){
				if(obj == IntPtr.Zero) {
					objPtr = VidyoNetworkServiceResponseHeaderConstructDefaultNative();
				}
				else {
					objPtr = VidyoNetworkServiceResponseHeaderConstructCopyNative(obj);
				}

				errorCode = VidyoNetworkServiceResponseHeaderGeterrorCodeNative(objPtr);
				httpResponseContent = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoNetworkServiceResponseHeaderGethttpResponseContentNative(objPtr));
				httpResponseContentSize = VidyoNetworkServiceResponseHeaderGethttpResponseContentSizeNative(objPtr);
				httpResponseContentType = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoNetworkServiceResponseHeaderGethttpResponseContentTypeNative(objPtr));
				httpStatusCode = VidyoNetworkServiceResponseHeaderGethttpStatusCodeNative(objPtr);
				requestNumber = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoNetworkServiceResponseHeaderGetrequestNumberNative(objPtr));
				webProxyIPAddress = (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(VidyoNetworkServiceResponseHeaderGetwebProxyIPAddressNative(objPtr));
				webProxyIPPort = VidyoNetworkServiceResponseHeaderGetwebProxyIPPortNative(objPtr);
			}
			~NetworkServiceResponseHeader() {
				VidyoNetworkServiceResponseHeaderDestructNative(objPtr);
			 }
		};
		private IHttpRequestASync _mIHttpRequestASync;
		public NetworkService(NetworkServiceCAInfo caInfo){

			objPtr = VidyoNetworkServiceConstructNative((caInfo != null) ? caInfo.GetObjectPtr():IntPtr.Zero);
			VidyoNetworkServiceSetUserDataNative(objPtr, GCHandle.ToIntPtr(GCHandle.Alloc(this, GCHandleType.Weak)));
		}
		public NetworkService(IntPtr other){
			objPtr = VidyoNetworkServiceConstructCopyNative(other);
			VidyoNetworkServiceSetUserDataNative(objPtr, GCHandle.ToIntPtr(GCHandle.Alloc(this, GCHandleType.Weak)));
		}
		~NetworkService(){
			Dispose(false);
		}
		public void Dispose(){
			Dispose(true);
			GC.SuppressFinalize(this);
		}

		public void Dispose(bool disposing){
			if(!disposed){
				if(objPtr != IntPtr.Zero){
					VidyoNetworkServiceSetUserDataNative(objPtr, IntPtr.Zero);
					VidyoNetworkServiceDestructNative(objPtr);
				}
				disposed = true;
			}
		}

		public NetworkServiceErrorCode HttpRequestASync(NetworkServiceRequestHeader requestHeader, IHttpRequestASync _iIHttpRequestASync, ulong userData){
			_mIHttpRequestASync = _iIHttpRequestASync;
			_mResponseCB = ResponseCBDelegate;

			NetworkServiceErrorCode ret = VidyoNetworkServiceHttpRequestASyncNative(objPtr, (requestHeader != null) ? requestHeader.GetObjectPtr():IntPtr.Zero, _mResponseCB, userData);

			return ret;
		}
#if __IOS__
[ObjCRuntime.MonoPInvokeCallback(typeof(ResponseCB))]
#endif
		private static void ResponseCBDelegate(IntPtr networkService, IntPtr httpResponseHeader, ulong userData){
			NetworkService csNetworkService = null;
			if(networkService != IntPtr.Zero){
				if(NetworkService.VidyoNetworkServiceGetUserDataNative(networkService) == IntPtr.Zero)
					csNetworkService = new NetworkService(networkService);
				else{
					GCHandle objHandle = (GCHandle)NetworkService.VidyoNetworkServiceGetUserDataNative(networkService);
					csNetworkService = (NetworkService)objHandle.Target;
				}
			}
			NetworkServiceResponseHeader csHttpResponseHeader = new NetworkServiceResponseHeader(httpResponseHeader);
			if(csNetworkService._mIHttpRequestASync != null)
				csNetworkService._mIHttpRequestASync.ResponseCB(csHttpResponseHeader, userData);
		}
	};
}
