// DO NOT EDIT! This is an autogenerated file. All changes will be
// overwritten!

//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Collections;
using System.Runtime.InteropServices;

namespace VidyoClient
{
	public class Participant: IDisposable {
		private bool disposed = false; 
#if __IOS__
		const string importLib = "__Internal";
#else
		const string importLib = "libVidyoClient";
#endif
		private IntPtr objPtr; // opaque VidyoParticipant reference.
		public IntPtr GetObjectPtr(){
			return objPtr;
		}
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoParticipantConstructCopyNative(IntPtr other);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoParticipantDestructNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I4)]
		private static extern ParticipantApplicationType VidyoParticipantGetApplicationTypeNative(IntPtr p);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I4)]
		private static extern ParticipantClearanceType VidyoParticipantGetClearanceTypeNative(IntPtr p);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoParticipantGetContactNative(IntPtr p, IntPtr contact);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I1)]
		private static extern Boolean VidyoParticipantGetContactAsyncNative(IntPtr p, OnGetContactComplete onComplete);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoParticipantGetIdNative(IntPtr p);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoParticipantGetNameNative(IntPtr p);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I4)]
		private static extern ParticipantTrust VidyoParticipantGetTrustNative(IntPtr p);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoParticipantGetUserIdNative(IntPtr p);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I1)]
		private static extern Boolean VidyoParticipantIsHiddenNative(IntPtr p);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I1)]
		private static extern Boolean VidyoParticipantIsLocalNative(IntPtr p);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I1)]
		private static extern Boolean VidyoParticipantIsRecordingNative(IntPtr p);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I1)]
		private static extern Boolean VidyoParticipantIsSelectableNative(IntPtr p);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		public static extern IntPtr VidyoParticipantGetUserDataNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		public static extern void VidyoParticipantSetUserDataNative(IntPtr obj, IntPtr userData);

		[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
		private delegate void OnGetContactComplete(IntPtr p, IntPtr contact, ParticipantGetContactResult result);
		private OnGetContactComplete _mOnGetContactComplete;
		public enum ParticipantApplicationType{
			ParticipantAPPLICATIONTYPE_None,
			ParticipantAPPLICATIONTYPE_Recorder,
			ParticipantAPPLICATIONTYPE_Gateway
		}
		public enum ParticipantClearanceType{
			ParticipantCLEARANCETYPE_None,
			ParticipantCLEARANCETYPE_Member,
			ParticipantCLEARANCETYPE_Owner,
			ParticipantCLEARANCETYPE_Admin,
			ParticipantCLEARANCETYPE_Moderator
		}
		public enum ParticipantGetContactResult{
			ParticipantgetcontactresultSUCCESS,
			ParticipantgetcontactresultMiscError
		}
		public enum ParticipantHandState{
			ParticipanthandstateUNRAISED,
			ParticipanthandstateRAISED,
			ParticipanthandstateAPPROVED,
			ParticipanthandstateDISMISSED
		}
		public enum ParticipantTrust{
			ParticipanttrustLocal,
			ParticipanttrustFederated,
			ParticipanttrustAnonymous
		}
		public interface IGetContactAsync{

			void OnGetContactComplete(Contact contact, ParticipantGetContactResult result);
		}
		private IGetContactAsync _mIGetContactAsync;
		public Participant(IntPtr other){
			objPtr = VidyoParticipantConstructCopyNative(other);
			VidyoParticipantSetUserDataNative(objPtr, GCHandle.ToIntPtr(GCHandle.Alloc(this, GCHandleType.Weak)));
		}
		public Participant(){
			Dispose(false);
		}
		public void Dispose(){
			Dispose(true);
			GC.SuppressFinalize(this);
		}

		public void Dispose(bool disposing){
			if(!disposed){
				if(objPtr != IntPtr.Zero){
					VidyoParticipantSetUserDataNative(objPtr, IntPtr.Zero);
					VidyoParticipantDestructNative(objPtr);
				}
				disposed = true;
			}
		}

		public virtual ParticipantApplicationType GetApplicationType(){

			ParticipantApplicationType ret = VidyoParticipantGetApplicationTypeNative(objPtr);

			return ret;
		}
		public ParticipantClearanceType GetClearanceType(){

			ParticipantClearanceType ret = VidyoParticipantGetClearanceTypeNative(objPtr);

			return ret;
		}
		public Contact GetContact(ref Contact contact){

			IntPtr ret = VidyoParticipantGetContactNative(objPtr, (contact != null) ? contact.GetObjectPtr():IntPtr.Zero);
			Contact csRet = new Contact(ret);

			contact = csRet;
			return csRet;
		}
		public Boolean GetContactAsync(IGetContactAsync _iIGetContactAsync){
			_mIGetContactAsync = _iIGetContactAsync;
			_mOnGetContactComplete = OnGetContactCompleteDelegate;

			Boolean ret = VidyoParticipantGetContactAsyncNative(objPtr, _mOnGetContactComplete);

			return ret;
		}
		public virtual String GetId(){

			IntPtr ret = VidyoParticipantGetIdNative(objPtr);

			return (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(ret);
		}
		public virtual String GetName(){

			IntPtr ret = VidyoParticipantGetNameNative(objPtr);

			return (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(ret);
		}
		public ParticipantTrust GetTrust(){

			ParticipantTrust ret = VidyoParticipantGetTrustNative(objPtr);

			return ret;
		}
		public virtual String GetUserId(){

			IntPtr ret = VidyoParticipantGetUserIdNative(objPtr);

			return (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(ret);
		}
		public Boolean IsHidden(){

			Boolean ret = VidyoParticipantIsHiddenNative(objPtr);

			return ret;
		}
		public Boolean IsLocal(){

			Boolean ret = VidyoParticipantIsLocalNative(objPtr);

			return ret;
		}
		public Boolean IsRecording(){

			Boolean ret = VidyoParticipantIsRecordingNative(objPtr);

			return ret;
		}
		public Boolean IsSelectable(){

			Boolean ret = VidyoParticipantIsSelectableNative(objPtr);

			return ret;
		}
#if __IOS__
[ObjCRuntime.MonoPInvokeCallback(typeof(OnGetContactComplete))]
#endif
		private static void OnGetContactCompleteDelegate(IntPtr p, IntPtr contact, ParticipantGetContactResult result){
			Participant csP = null;
			if(p != IntPtr.Zero){
				if(Participant.VidyoParticipantGetUserDataNative(p) == IntPtr.Zero)
					csP = new Participant(p);
				else{
					GCHandle objHandle = (GCHandle)Participant.VidyoParticipantGetUserDataNative(p);
					csP = (Participant)objHandle.Target;
				}
			}
			Contact csContact = new Contact(contact);
			if(csP._mIGetContactAsync != null)
				csP._mIGetContactAsync.OnGetContactComplete(csContact, result);
		}
	};
}
