// DO NOT EDIT! This is an autogenerated file. All changes will be
// overwritten!

//	Copyright (c) 2016 Vidyo, Inc. All rights reserved.


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Collections;
using System.Runtime.InteropServices;

namespace VidyoClient
{
	public class RemoteCamera: IDisposable {
		private bool disposed = false; 
#if __IOS__
		const string importLib = "__Internal";
#else
		const string importLib = "libVidyoClient";
#endif
		private IntPtr objPtr; // opaque VidyoRemoteCamera reference.
		public IntPtr GetObjectPtr(){
			return objPtr;
		}
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I1)]
		private static extern Boolean VidyoRemoteCameraActivatePresetNative(IntPtr c, uint index);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoRemoteCameraAddToLocalRendererNative(IntPtr c, IntPtr localRenderer, [MarshalAs(UnmanagedType.I4)]RemoteCameraMode mode);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoRemoteCameraConstructCopyNative(IntPtr other);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I1)]
		private static extern Boolean VidyoRemoteCameraControlPTZNudgeNative(IntPtr c, int pan, int tilt, int zoom);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I1)]
		private static extern Boolean VidyoRemoteCameraControlPTZStartNative(IntPtr c, [MarshalAs(UnmanagedType.I4)]CameraControlCapabilities.CameraControlDirection direction, ulong timeout);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I1)]
		private static extern Boolean VidyoRemoteCameraControlPTZStopNative(IntPtr c);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern void VidyoRemoteCameraDestructNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoRemoteCameraGetControlCapabilitiesNative(IntPtr c);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoRemoteCameraGetIdNative(IntPtr c);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern ulong VidyoRemoteCameraGetLocalRenderingStreamIdNative(IntPtr c, int index);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoRemoteCameraGetNameNative(IntPtr c);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I4)]
		private static extern RemoteCameraPosition VidyoRemoteCameraGetPositionNative(IntPtr c);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I1)]
		private static extern Boolean VidyoRemoteCameraIsControllableNative(IntPtr c);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I1)]
		private static extern Boolean VidyoRemoteCameraRegisterFrameEventListenerNative(IntPtr c, OnRemoteCameraFrame onFrame);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I1)]
		private static extern Boolean VidyoRemoteCameraRegisterFrameSizeListenerNative(IntPtr c, OnFrameSizeUpdate onFrameSizeUpdate);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I1)]
		private static extern Boolean VidyoRemoteCameraRegisterPresetEventListenerNative(IntPtr c, OnPresetUpdated onPresetUpdated);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I1)]
		private static extern Boolean VidyoRemoteCameraRemoveFromLocalRendererNative(IntPtr c, IntPtr localRenderer);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I1)]
		private static extern Boolean VidyoRemoteCameraSetPositionInLocalRendererNative(IntPtr c, IntPtr localRenderer, int x, int y, uint width, uint height, ulong frameInterval);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I1)]
		private static extern Boolean VidyoRemoteCameraShowCameraControlNative(IntPtr c, Boolean show);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I1)]
		private static extern Boolean VidyoRemoteCameraUnregisterFrameEventListenerNative(IntPtr c);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I1)]
		private static extern Boolean VidyoRemoteCameraUnregisterFrameSizeListenerNative(IntPtr c);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I1)]
		private static extern Boolean VidyoRemoteCameraUnregisterPresetEventListenerNative(IntPtr c);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I1)]
		private static extern Boolean VidyoRemoteCameraViscaControlNative(IntPtr c, IntPtr viscaCmd, IntPtr viscaCmdId);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		public static extern IntPtr VidyoRemoteCameraGetUserDataNative(IntPtr obj);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		public static extern void VidyoRemoteCameraSetUserDataNative(IntPtr obj, IntPtr userData);

		[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
		private delegate void OnFrameSizeUpdate(IntPtr c, [MarshalAs(UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(SizeTMarshaler))]SizeT width, [MarshalAs(UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(SizeTMarshaler))]SizeT height);
		private OnFrameSizeUpdate _mOnFrameSizeUpdate;
		[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
		private delegate void OnPresetUpdated(IntPtr c, IntPtr presets);
		private OnPresetUpdated _mOnPresetUpdated;
		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoRemoteCameraOnPresetUpdatedGetpresetsArrayNative(IntPtr obj, ref int size);

		[DllImport(importLib, CallingConvention = CallingConvention.Cdecl)]
		private static extern IntPtr VidyoRemoteCameraOnPresetUpdatedFreepresetsArrayNative(IntPtr obj, int size);

		[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
		private delegate void OnRemoteCameraFrame(IntPtr c, IntPtr participant, IntPtr videoFrame);
		private OnRemoteCameraFrame _mOnRemoteCameraFrame;
		public enum RemoteCameraMode{
			RemotecameramodeDynamic,
			RemotecameramodeStatic
		}
		public enum RemoteCameraPosition{
			RemotecamerapositionUnknown,
			RemotecamerapositionFront,
			RemotecamerapositionBack
		}
		public interface IRegisterFrameEventListener{

			void OnRemoteCameraFrame(Participant participant, VideoFrame videoFrame);
		}
		public interface IRegisterFrameSizeListener{

			void OnFrameSizeUpdate(SizeT width, SizeT height);
		}
		public interface IRegisterPresetEventListener{

			void OnPresetUpdated(List<CameraPreset> presets);
		}
		private IRegisterFrameEventListener _mIRegisterFrameEventListener;
		private IRegisterFrameSizeListener _mIRegisterFrameSizeListener;
		private IRegisterPresetEventListener _mIRegisterPresetEventListener;
		public RemoteCamera(IntPtr other){
			objPtr = VidyoRemoteCameraConstructCopyNative(other);
			VidyoRemoteCameraSetUserDataNative(objPtr, GCHandle.ToIntPtr(GCHandle.Alloc(this, GCHandleType.Weak)));
		}
		~RemoteCamera(){
			Dispose(false);
		}
		public void Dispose(){
			Dispose(true);
			GC.SuppressFinalize(this);
		}

		public void Dispose(bool disposing){
			if(!disposed){
				if(objPtr != IntPtr.Zero){
					VidyoRemoteCameraSetUserDataNative(objPtr, IntPtr.Zero);
					VidyoRemoteCameraDestructNative(objPtr);
				}
				disposed = true;
			}
		}

		public Boolean ActivatePreset(uint index){

			Boolean ret = VidyoRemoteCameraActivatePresetNative(objPtr, index);

			return ret;
		}
		public ulong AddToLocalRenderer(LocalRenderer localRenderer, RemoteCameraMode mode){

			ulong ret = VidyoRemoteCameraAddToLocalRendererNative(objPtr, (localRenderer != null) ? localRenderer.GetObjectPtr():IntPtr.Zero, mode);

			return ret;
		}
		public Boolean ControlPTZNudge(int pan, int tilt, int zoom){

			Boolean ret = VidyoRemoteCameraControlPTZNudgeNative(objPtr, pan, tilt, zoom);

			return ret;
		}
		public Boolean ControlPTZStart(CameraControlCapabilities.CameraControlDirection direction, ulong timeout){

			Boolean ret = VidyoRemoteCameraControlPTZStartNative(objPtr, direction, timeout);

			return ret;
		}
		public Boolean ControlPTZStop(){

			Boolean ret = VidyoRemoteCameraControlPTZStopNative(objPtr);

			return ret;
		}
		public CameraControlCapabilities GetControlCapabilities(){

			IntPtr ret = VidyoRemoteCameraGetControlCapabilitiesNative(objPtr);
			CameraControlCapabilities csRet = new CameraControlCapabilities(ret);

			return csRet;
		}
		public String GetId(){

			IntPtr ret = VidyoRemoteCameraGetIdNative(objPtr);

			return (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(ret);
		}
		public ulong GetLocalRenderingStreamId(int index){

			ulong ret = VidyoRemoteCameraGetLocalRenderingStreamIdNative(objPtr, index);

			return ret;
		}
		public String GetName(){

			IntPtr ret = VidyoRemoteCameraGetNameNative(objPtr);

			return (string)MarshalPtrToUtf8.GetInstance().MarshalNativeToManaged(ret);
		}
		public RemoteCameraPosition GetPosition(){

			RemoteCameraPosition ret = VidyoRemoteCameraGetPositionNative(objPtr);

			return ret;
		}
		public Boolean IsControllable(){

			Boolean ret = VidyoRemoteCameraIsControllableNative(objPtr);

			return ret;
		}
		public Boolean RegisterFrameEventListener(IRegisterFrameEventListener _iIRegisterFrameEventListener){
			_mIRegisterFrameEventListener = _iIRegisterFrameEventListener;
			_mOnRemoteCameraFrame = OnRemoteCameraFrameDelegate;

			Boolean ret = VidyoRemoteCameraRegisterFrameEventListenerNative(objPtr, _mOnRemoteCameraFrame);

			return ret;
		}
		public Boolean RegisterFrameSizeListener(IRegisterFrameSizeListener _iIRegisterFrameSizeListener){
			_mIRegisterFrameSizeListener = _iIRegisterFrameSizeListener;
			_mOnFrameSizeUpdate = OnFrameSizeUpdateDelegate;

			Boolean ret = VidyoRemoteCameraRegisterFrameSizeListenerNative(objPtr, _mOnFrameSizeUpdate);

			return ret;
		}
		public Boolean RegisterPresetEventListener(IRegisterPresetEventListener _iIRegisterPresetEventListener){
			_mIRegisterPresetEventListener = _iIRegisterPresetEventListener;
			_mOnPresetUpdated = OnPresetUpdatedDelegate;

			Boolean ret = VidyoRemoteCameraRegisterPresetEventListenerNative(objPtr, _mOnPresetUpdated);

			return ret;
		}
		public Boolean RemoveFromLocalRenderer(LocalRenderer localRenderer){

			Boolean ret = VidyoRemoteCameraRemoveFromLocalRendererNative(objPtr, (localRenderer != null) ? localRenderer.GetObjectPtr():IntPtr.Zero);

			return ret;
		}
		public Boolean SetPositionInLocalRenderer(LocalRenderer localRenderer, int x, int y, uint width, uint height, ulong frameInterval){

			Boolean ret = VidyoRemoteCameraSetPositionInLocalRendererNative(objPtr, (localRenderer != null) ? localRenderer.GetObjectPtr():IntPtr.Zero, x, y, width, height, frameInterval);

			return ret;
		}
		public Boolean ShowCameraControl(Boolean show){

			Boolean ret = VidyoRemoteCameraShowCameraControlNative(objPtr, show);

			return ret;
		}
		public Boolean UnregisterFrameEventListener(){

			Boolean ret = VidyoRemoteCameraUnregisterFrameEventListenerNative(objPtr);

			return ret;
		}
		public Boolean UnregisterFrameSizeListener(){

			Boolean ret = VidyoRemoteCameraUnregisterFrameSizeListenerNative(objPtr);

			return ret;
		}
		public Boolean UnregisterPresetEventListener(){

			Boolean ret = VidyoRemoteCameraUnregisterPresetEventListenerNative(objPtr);

			return ret;
		}
		public Boolean ViscaControl(String viscaCmd, String viscaCmdId){

			IntPtr nViscaCmd = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(viscaCmd ?? string.Empty);
			IntPtr nViscaCmdId = MarshalPtrToUtf8.GetInstance().MarshalManagedToNative(viscaCmdId ?? string.Empty);
			Boolean ret = VidyoRemoteCameraViscaControlNative(objPtr, nViscaCmd, nViscaCmdId);
			Marshal.FreeHGlobal(nViscaCmdId);
			Marshal.FreeHGlobal(nViscaCmd);

			return ret;
		}
#if __IOS__
[ObjCRuntime.MonoPInvokeCallback(typeof(OnFrameSizeUpdate))]
#endif
		private static void OnFrameSizeUpdateDelegate(IntPtr c, [MarshalAs(UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(SizeTMarshaler))]SizeT width, [MarshalAs(UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(SizeTMarshaler))]SizeT height){
			RemoteCamera csC = null;
			if(c != IntPtr.Zero){
				if(RemoteCamera.VidyoRemoteCameraGetUserDataNative(c) == IntPtr.Zero)
					csC = new RemoteCamera(c);
				else{
					GCHandle objHandle = (GCHandle)RemoteCamera.VidyoRemoteCameraGetUserDataNative(c);
					csC = (RemoteCamera)objHandle.Target;
				}
			}
			if(csC._mIRegisterFrameSizeListener != null)
				csC._mIRegisterFrameSizeListener.OnFrameSizeUpdate(width, height);
		}
#if __IOS__
[ObjCRuntime.MonoPInvokeCallback(typeof(OnPresetUpdated))]
#endif
		private static void OnPresetUpdatedDelegate(IntPtr c, IntPtr presets){
			RemoteCamera csC = null;
			if(c != IntPtr.Zero){
				if(RemoteCamera.VidyoRemoteCameraGetUserDataNative(c) == IntPtr.Zero)
					csC = new RemoteCamera(c);
				else{
					GCHandle objHandle = (GCHandle)RemoteCamera.VidyoRemoteCameraGetUserDataNative(c);
					csC = (RemoteCamera)objHandle.Target;
				}
			}
			List<CameraPreset> csPresets = new List<CameraPreset>();
			int nPresetsSize = 0;
			IntPtr nPresets = VidyoRemoteCameraOnPresetUpdatedGetpresetsArrayNative(presets, ref nPresetsSize);
			int nPresetsIndex = 0;
			while (nPresetsIndex < nPresetsSize) {
				CameraPreset csTpresets = new CameraPreset(Marshal.ReadIntPtr(nPresets + (nPresetsIndex * Marshal.SizeOf(nPresets))));
				csPresets.Add(csTpresets);
				nPresetsIndex++;
			}

			if(csC._mIRegisterPresetEventListener != null)
				csC._mIRegisterPresetEventListener.OnPresetUpdated(csPresets);
			VidyoRemoteCameraOnPresetUpdatedFreepresetsArrayNative(nPresets, nPresetsSize);
		}
#if __IOS__
[ObjCRuntime.MonoPInvokeCallback(typeof(OnRemoteCameraFrame))]
#endif
		private static void OnRemoteCameraFrameDelegate(IntPtr c, IntPtr participant, IntPtr videoFrame){
			RemoteCamera csC = null;
			if(c != IntPtr.Zero){
				if(RemoteCamera.VidyoRemoteCameraGetUserDataNative(c) == IntPtr.Zero)
					csC = new RemoteCamera(c);
				else{
					GCHandle objHandle = (GCHandle)RemoteCamera.VidyoRemoteCameraGetUserDataNative(c);
					csC = (RemoteCamera)objHandle.Target;
				}
			}
			Participant csParticipant = null;
			if(participant != IntPtr.Zero){
				if(Participant.VidyoParticipantGetUserDataNative(participant) == IntPtr.Zero)
					csParticipant = new Participant(participant);
				else{
					GCHandle objHandle = (GCHandle)Participant.VidyoParticipantGetUserDataNative(participant);
					csParticipant = (Participant)objHandle.Target;
				}
			}
			VideoFrame csVideoFrame = null;
			if(videoFrame != IntPtr.Zero){
				if(VideoFrame.VidyoVideoFrameGetUserDataNative(videoFrame) == IntPtr.Zero)
					csVideoFrame = new VideoFrame(videoFrame);
				else{
					GCHandle objHandle = (GCHandle)VideoFrame.VidyoVideoFrameGetUserDataNative(videoFrame);
					csVideoFrame = (VideoFrame)objHandle.Target;
				}
			}
			if(csC._mIRegisterFrameEventListener != null)
				csC._mIRegisterFrameEventListener.OnRemoteCameraFrame(csParticipant, csVideoFrame);
		}
	};
}
