@startmindmap
'https://plantuml.com/mindmap-diagram

title 莱塞思Windows客户端功能表

header
1.03.02
endheader

* 软件功能

** 参数启动
***[#lightgreen] 自动开始录制

** 小窗模式
*** 基础功能
****[#lightgreen] 布局
****[#lightgreen] 还原按钮
****[#lightgreen] 结束会议
****[#lightgreen] 禁音、禁摄
****[#lightgreen] 禁止窗口尺寸拖拽、最大化
*** 变换至小窗
****[#lightgreen] 主动操作（小图标右键）
****[#lightgreen] 开始共享（并置顶、终端模式不适用）
****[#lightgreen] 同步按钮状态（停止共享、禁用设备）
****[#lightgreen] 参数启动，入会即小窗
**** 大窗拖拽尺寸到阈值触发小窗
*** 变换回大窗
****[#lightgreen] 主动
****[#lightgreen] 退会
****[#lightgreen] 停止共享
*** 其他
****[#lightgreen] 小窗时，脱离WebUI尺寸同步的控制
****[#lightgreen] 通知栏开启小窗按钮仅在入会后显示

** 房间
*** 密码
**** 加入密码
***** 入会验证
***** 显示密码状态
***** 创建更新房间密码
***** 删除房间密码
**** 管理员密码
***** 入会验证
***** 显示密码状态
***** 创建更新密码
***** 删除密码
**** 模式切换

** 视频
*** 布局
**** 布局机制
***** 【优化】当有渲染源停止渲染时，先判断是否有无空闲源，如果有则触发渲染空闲源逻辑，如果无，则把后面的渲染往前移
**** 固定主摄（到1屏）
***** 取消固定后，将上个讲话人渲染到主屏
***** bug
****** （多人共享）：当我先共享和A也发共享后，我关闭共享，A共享到主屏了，但A摄像没到主屏
****** （细节后续补充）：当演讲者在主屏时，然后固定主摄，此时演讲者应去到第二屏新语音激励位置
*** 共享屏幕
**** 开启音频选项
*** 显示网络质量

** 操作界面
*** Title显示Tango连接状态

**[#lightgreen] 录制
*** 入会后需要查询一次录制状态
*** 开始录制后，其他参会者录制状态同步
*** 录制者退会时应停止录制
*** 录制结束后，提示回看地址
*** 录制操作后获取状态需要延迟获取

caption TangoWin
center footer 2024-1-17

legend right
  备注
endlegend
@endmindmap
