//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidyoConnector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VideoClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您的电脑未安装 .NET Framework 运行时库，无法运行软件，请安装后再尝试打开软件.
        /// </summary>
        internal static string alert_dot_net_framework_not_exist {
            get {
                return ResourceManager.GetString("alert_dot_net_framework_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您安装的软件与您的操作系统版本不匹配，请下载与您系统相对应的软件进行使用。如Windows10或11需要安装win10软件包，Windows7需要安装win7软件包。.
        /// </summary>
        internal static string alert_is_os_not_compatible_with_app {
            get {
                return ResourceManager.GetString("alert_is_os_not_compatible_with_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 端口已被占用，请检查或联系管理员。.
        /// </summary>
        internal static string alert_port_is_in_used {
            get {
                return ResourceManager.GetString("alert_port_is_in_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您的电脑未安装 VC++2015-2019 或者 VC++2015-2022 运行时库，请安装后再尝试打开软件.
        /// </summary>
        internal static string alert_vc_runtime_not_exist {
            get {
                return ResourceManager.GetString("alert_vc_runtime_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 程序已运行，不能再次打开！.
        /// </summary>
        internal static string program_not_allow_open_twice {
            get {
                return ResourceManager.GetString("program_not_allow_open_twice", resourceCulture);
            }
        }
    }
}
